name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Inject environment variables
        env:
          REPO_NAME: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          sed -i "s|\${{ secrets.REPO_NAME }}|$REPO_NAME|g" config.js
          sed -i "s|\${{ secrets.GH_TOKEN }}|$GH_TOKEN|g" config.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: .
          force_orphan: true
